services:
  astro-vault:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
      - PORT=4321
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4321/', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
